### PR TITLE
add optional TFDT support

### PR DESCRIPTION
**Pull request by blld**
Optionally Add `TFDT` to `TRAF`, so that the resulting fMP4 is compatible with https://www.w3.org/TR/mse-byte-stream-format-isobmff/ and can be played from a `SourceBuffer` in `MediaSource`.

The change is made to change nothing by default, and be enabled with a simple flag.

Resulting fMP4 played successfully with MediaSource on:
- Safari
- Firefox
- Chrome
- Edge

### CODE REVIEW

**Comment by blld** [comment]
note that this change fix https://github.com/lieff/minimp4/issues/3

**Comment by lieff** [comment]
Cool :)
I've never tested it in browsers before.
Do you know easiest way how to test resulting file on browser?

**Comment by blld** [comment]
@lieff Thanks !

Sorry for the late reply.
To test you can `base64` the resulting file, and put it in a html of the like:

```html
<!DOCTYPE html>
<html>
<head></head>

<body>
<script>
var v = '<base64 of the video here>'

var base64Table = new Uint8Array(0x7F),
    base64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/='

base64.split('').map(function(value,index){ base64Table[value.charCodeAt(0)] = index })

function atob(data)
{
    var length = data.length,
        padding = data.charCodeAt(length - 2) == 61? 2: data.charCodeAt(length - 1) == 61? 1: 0,
        size = (length * 3) / 4 - padding,
        out = new Uint8Array(size)
    
    for (var i = 0, o = 0; o < size; o += 3)
    {
        var a = base64Table[data.charCodeAt(i++)],
            b = base64Table[data.charCodeAt(i++)],
            c = base64Table[data.charCodeAt(i++)],
            d = base64Table[data.charCodeAt(i++)]
        out[o] = (a << 2) | (b >> 4)
        if (o + 1 < size) out[o + 1] = ((b & 15) << 4) | (c >> 2)
        if (o + 2 < size) out[o + 2] = ((c & 3) << 6) | d
    }
    return out
}


var mimeCodec = 'video/mp4; codecs="avc1.42C00A"' // <-- the proper video codec here
if (MediaSource.isTypeSupported(mimeCodec)) {
    var video = document.createElement('video'),
        mediaSource = new MediaSource()
    mediaSource.onsourceopen = function(){
        var sourceBuffer = mediaSource.addSourceBuffer(mimeCodec)
        sourceBuffer.appendBuffer(atob(v))
    }
    video.src = URL.createObjectURL(mediaSource)
    video.muted = true
    video.play()
    document.body.appendChild(video)
}
</script>
</body>
</html>
```

You could split by `moof` and feed sourceBuffer one frame at a time also, it works :)

**Comment by lieff** [comment]
Thanks for the sample) Works great!

**Pull request merged**
